### ISSUE TITLE
Issue with sed command in GWAS pipeline

### ISSUE THREAD

**Issue by montenegrina** [neurogenetics/GWAS-pipeline#2]
Hi,

I was running this command in your pipeline:

sed 's/|/\/g' missing_haps_1E7.txt > missing_haps_1E7_final.txt
sed: -e expression #1, char 7: unterminated `s' command

head missing_haps_1E7.txt
1:3925928:G:A|1:3929593:T:C
1:4359549:T:C|1:4360122:C:T
1:4359563:C:T|1:4360565:T:C
1:4459761:T:C|1:4461905:C:T
...

Can you please let me know how this sed command should look like?

Thanks
Ana

**Comment by montenegrina** [comment]
I plan to run this afterweards:
plink --bfile output5 --exclude missing_haps_1E4_final.txt --make-bed --out output5F

where my output5.bim looks like this:
1	1:775852:T:C	0	775852	T	C
1	1:1120590:A:C	0	1120590	C	A
1	1:1145994:T:C	0	1145994	C	T
1	1:1148494:A:G	0	1148494	A	G

**Comment by CornelisB** [comment]
Hi sorry for late reply didnt see this... what is your OS? sed can be a bit different depending on OS... mac/linux have minor differences

**Comment by montenegrina** [comment]
Hi,

I'm running this on x86_64 x86_64 x86_64 GNU/Linux

Thanks
Ana

**Comment by CornelisB** [comment]
sed 's/|/\n/g' missing_haps_1E4.txt > missing_haps_1E4_final.txt

this should work... the "n" was missing to start a new line...
Basically this transforms the haplotype SNP format => rs367702628|rs6660590|etc|etc to a single variant per line and then you can exclude these...
